spring.application.name=mastersys


#Banco de dados postgres
spring.datasource.url = jdbc:postgresql://localhost:5432/academia
spring.datasource.username=postgres
spring.datasource.password=Java@2023
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true


#Configurações do Flyway
#Assegura que o Flyway seja executado automaticamente na inicialização da aplicação
#flyway será responsável por aplicar as migrações de banco de dados \
#é um gerenciador de migrações de banco de dados que ajuda a manter o \
#esquema do banco de dados atualizado com as mudanças no código da aplicação.

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# caso altere o DDL de alguma entidade
# UPDATE flyway_schema_history
# SET checksum = 1915736264  -- esse valor é o checksum gerado pelo Flyway para a versão da migração ( > Resolved locally    : 1915736264 )
# WHERE version = '1';