spring.application.name=mastersys


#Banco de dados postgres
spring.datasource.url = jdbc:postgresql://localhost:5432/academia
spring.datasource.username=postgres
spring.datasource.password=java@2023
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

// Configurações do Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

